### ISSUE TITLE
PDF of help files/documentation, examples of integrated code

### ISSUE THREAD

**Issue by EllaBowles** [thierrygosselin/stackr#21]
Hello,

This package is amazing in its completeness. I'm wondering if there is anywhere that I can find anyone's code, who has used the package for a series of analyses, so that I can get a sense for how to implement the workflow that is provided, and how to integrate the various functions (perhaps from the Benestan paper)? Also, I've read through a whole bunch of the help files for a whole lot of functions, but is there a way that I can get all the functions in a single PDF, sort of as documentation? 

Many thanks for this great package.
Ella

**Comment by thierrygosselin** [comment]
Hi Ella, 

- **Codes and documentation**: The package is still in development and vignettes will be included regularly. Coming next week: `imputations`. That follows on the missing data visualization and analysis [vignette](https://www.dropbox.com/s/4zf032g6yjatj0a/vignette_missing_data_analysis.nb.html?dl=0).
I'm trying to figure out how to organise the function in one document. Will keep you informed of progress. Paper will be submitted this summer.
- **Benestan paper**: `stackr` was not invented at the time of the lobster paper. [assigner](https://github.com/thierrygosselin/assigner) was created for the erratum of the lobster paper. 

- **Workflows**: I usually follow this [workflow](https://github.com/thierrygosselin/stackr#stackr-workflow)

Best,
Thierry

**Comment by thierrygosselin** [comment]
I think that students in Louis's lab are using [this approach](https://github.com/enormandeau/stacks_workflow).
