### ISSUE TITLE
Error installing stackr

### ISSUE THREAD

**Issue by danifermch** [thierrygosselin/stackr#22]
When installing the stackr from Rstudio using the #devtools::install_github("thierrygosselin/stackr")# line, I get the following error

* installing *source* package 'stackr' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'assertthat'
ERROR: lazy loading failed for package 'stackr'
* removing 'C:/Users/uno/Documents/R/win-library/3.4/stackr'
Error: Command failed (1)

I have the last version of R (x64), Rstudio and Rtools.
Attached you can check the full log.

[Error.R.txt](https://github.com/thierrygosselin/stackr/files/954019/Error.R.txt)

**Comment by thierrygosselin** [comment]
`assertthat` is a the problematic package during you're install. It's probably a dependencies of `stackr` dependencies. Will require more check. 

In the mean time just install `asserthat` with `install.packages("assertthat")` and try again installing `stackr`
