### ISSUE TITLE
error in summary_ustacks

### ISSUE THREAD

**Issue by crisale84** [thierrygosselin/stackr#23]
Hi Thierry,
I am using your stackr to do my pictures, but now I have this error, I run stacks in a cluster, and I am trying to do my summarizes in my local Rstudio, can you help me with this?
Thank you for your time

> ustacks.summary<- summary_ustacks(
+   ustacks.folder= "./denovo_M1/",
+  # parallel.core = parallel::detectCores() -1,
+   filename = "./denovo_M1/",
+   verbose = TRUE)
#######################################################################
#######################################################################
Removing these catalog files from the summary:
  catalog.alleles.tsv.gz
  catalog.calls
  catalog.fa.gz
  catalog.snps.tsv.gz
  catalog.tags.tsv.gz
Summarizing 8 ustacks (snps, tags, alleles) files...

Summarizing information...
  |                                                  |   0%, ETA NA
Error: Argument 1 must have names
In addition: Warning message:
In .stackr_parallel(X = sample.name, FUN = summarise_ustacks, mc.cores = parallel.core,  :
  scheduled cores encountered errors in user code

**Comment by thierrygosselin** [comment]
Try this and tell me if you still get an error:

```
library(stackr)
setwd("YOUR WORKING DIRECTORY")
test1 <- stackr::summary_ustacks(
  ustacks.folder = "./denovo_M1", 
  parallel.core = 1, 
  verbose = TRUE
  )
```

Depending if this work you could increase the number of core used. 
The other problem I see is that you're using the same value for the argument `ustacks.folder ` and the `filename`. In this case filename is pointing towards a directory not the actual name you want...

**Comment by crisale84** [comment]
Hi Thierry, now I have this message:

> test1 <- stackr::summary_ustacks(
+   ustacks.folder = "./denovo_M1", 
+   parallel.core = 1, 
+   verbose = TRUE
+ )
#######################################################################
##################### stackr::summary_ustacks #########################
#######################################################################
Removing these catalog files from the summary: 
  catalog.alleles.tsv.gz
  catalog.calls
  catalog.fa.gz
  catalog.snps.tsv.gz
  catalog.tags.tsv.gz
Summarizing 8 ustacks (snps, tags, alleles) files...

Summarizing information...
Error in .setMaxGlobalSize(max.vector.size) : 
  could not find function ".setMaxGlobalSize"

**Comment by thierrygosselin** [comment]
[Read this to fix this issue with R](https://thierrygosselin.github.io/radiator/articles/rad_genomics_computer_setup.html#error--setmaxglobalsize)

Feel free to re-open this issue if you still have a problem
