### ISSUE TITLE
Problem with run_process_radtags

### ISSUE THREAD

**Issue by teddy-urvois** [thierrygosselin/stackr#25]
Hi Thierry,

I have trouble running the cstacks command line with my samples, but it worked with RADproc. I was already using stackr for fasqcr, but I would like to use stackr for the whole workflow instead of switching from command line to R.

However, I have trouble with run_process_radtags. I am doing RADseq with paired end, so my project.info file is expected to have four columns Barcodes, Individuals, Forward and Reverse. Each of my individual is identified by a specific pair of barcodes (one at each end of the sequence). How am I supposed to give both barcodes with only one column?

Thank you in advance,

Teddy Urvois

**Comment by thierrygosselin** [comment]
Hi Teddy, 

For now, stackr will only work with paired-end dataset where paired end are found in separate file and just one set of barcodes. This is what I used in one of my project. I don’t really have the time to modify and give more options, my advice is to use stacks directly for your project. Sorry.

Best,
Thierry
